FROM python:3.7.12-slim-buster

# Set timezone (used for cron and poi code)
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone \
&& dpkg-reconfigure -f noninteractive tzdata \
# apt dependencies
&& apt-get update && apt-get install -y binutils libproj-dev gdal-bin cron locales libspatialindex-dev netcat \
&& locale-gen en_US.UTF-8 \
&& rm -rf /var/lib/apt/lists/*

# Copy requirements.txt
COPY requirements.txt .

RUN pip install -r requirements.txt
