# Generated by Django 3.2.9 on 2021-11-20 17:16

from django.db import migrations


def add_perm_to_supervisor(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    group, created = Group.objects.get_or_create(name='supervisor')
    permissions = ["change_fuelrequest", "view_fuelrequest"]
    for perm in Permission.objects.filter(codename__in=permissions):
        group.permissions.add(perm)

class Migration(migrations.Migration):

    dependencies = [
        ('Fuel', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_perm_to_supervisor, reverse_code=migrations.RunPython.noop),
    ]
